version: "3.8"

services:
  web:
    build: .
    command: gunicorn SMDR.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
