version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
     - '5432'

  health-project:
    build:
      context: .
    image: health-project
    expose:
    - "8001"
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

    entrypoint: /app/entryfile.sh
    command: python manage.py runserver 0.0.0.0:8000
