# Generated by Django 3.0 on 2022-08-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_relatives'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
